name: Build and Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Copy built bundle to built branch
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  git branch built || true
                  git checkout built
                  git rm -rf .
                  cp -R built/* .
                  rm -rf built/ node_modules/
                  git add .
                  git commit -m "Automatic build from {${{github.sha}}.slice(0, 7)}"
                  git push origin built --force
